---
url:         http://trans.github.com
source:      ./_source
destination: ./_site
plugins:     ./_plugins
layouts:     ../_layouts
include:     ['.htaccess']
exclude:     [Rakefile,Rulefile,LICENSE,Gemfile,Gemfile.lock,README.md,_Header,_Sidebar]
timezone:    nil

future:      false
show_drafts: nil
limit_posts: 0
pygments:    true

relative_permalinks: true

permalink:     pretty
paginate_path: 'page:num'
paginate: 10

markdown:      redcarpet #maruku
markdown_ext:  markdown,mkd,mkdn,md
textile_ext:   textile

excerpt_separator: "<!-- more -->"

safe:        false
host:        0.0.0.0
port:        4000
baseurl:     /
lsi:         false

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex

rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  use_coderay: false

  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style

redcloth:
  hard_breaks: true

#
# jekyll-assets: see more at https://github.com/ixti/jekyll-assets
#
assets:
  dirname: assets
  baseurl: /assets/
  sources:
    - ../_assets/javascripts
    - ../_assets/stylesheets
    - ../_assets/images
  js_compressor: uglifier
  css_compressor: sass
  cachebust: none
  cache: false
  gzip: [ text/css, application/javascript ]
  debug: false

#
# jekyll-gollum: see more at https://github.com/rubyworks/jekyll-gollum
#
gollum:
  folder: '../_wiki'
  page_yaml:
    layout: page
    author: trans
  post_yaml:
    layout: post
    author: trans

#
# Jekyll-incorporated:
#
inc:
  # Blog Information
  title:        "TRANSCODE"
  subtitle:     "Trans Technology and Programming Blog"
  cover_image:  blog-cover.jpg
  logo:         trans-logo.png

  # Company information
  company:      TRANS
  url:          http://transcode.github.com
  facebook:     ~  # tabcomputing
  twitter:      transgigamic
  gplus:        111585036010126099008
  about_link:   /About/

  # Product Information
  #product_link: http://incorporated.sendtoinc.com/
  #tagline:      "Get a modern blog for your company"
  product_link: http://github.com/trans
  tagline:      "Check out all of my open source work"

  # Comments
  disqus:
    # Eg. "exampleblog" Set to false to disable comments
    shortname:  false

  # Sharing settings
  sharing:
    twitter:    true
    facebook:   false
    gplus:      true
    hn:         true
 
  # Analytics
  analytics:
    google: 
      # eg. 'UA-123-12'
      id:       false

  # Google Fonts
  # eg. 'Droid+Sans:400,700|Droid+Serif:400,700'
  google_font: 'Droid+Sans:400,700'
  
  # Setup your fonts, colors etc at _assets/stylesheets/main.scss

